[package]
name = "kaori"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
ordered-float = "5.1.0"
criterion = "0.5"

[[bench]]
name="interpreter_bench"
harness=false

[profile.release]
debug = true
